FROM public.ecr.aws/lambda/python:3.12

# 1. Copy only requirements first
COPY requirements-lambda.txt /tmp/requirements-lambda.txt

# 2. Install dependencies
RUN pip install --no-cache-dir -r /tmp/requirements-lambda.txt

# 3. Now copy the full source code
COPY . ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.lambda_handler" ]