name: Website build/deploy job

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/webapp.yaml'
      - 'webapp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Package install
        working-directory: webapp
        run: npm install

      - name: App build
        working-directory: webapp
        env:
          VITE_API_ENDPOINT: ${{ vars.VITE_API_ENDPOINT }}
        run: NODE_ENV=production npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        working-directory: webapp
        env:
          S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        run: |
          aws s3 sync ./dist s3://$S3_BUCKET_NAME/ --delete